About_content: "\u8BF7\u53C2\u8003\uFF1Ahttps://github.com/pengxiao-song/ti4all"
AllowMultiCore: false
Connect_content: "\u8BF7\u53C2\u8003\uFF1Ahttps://github.com/pengxiao-song/ti4all"
ImgDir: images
InfoFile: template.xlsx
